// (c) +KZ
#ifndef GAME_MAPITEMS_KZ_H
#define GAME_MAPITEMS_KZ_H

#include <game/mapitems.h>
#include <game/generated/protocol.h>

const char KZ_GAME_LAYER_NAME[9] = {'+','K', 'Z', 'G', 'a', 'm', 'e', (char)27, '\0'};
const char KZ_FRONT_LAYER_NAME[10] = {'+','K', 'Z', 'F', 'r', 'o', 'n', 't', (char)27, '\0'};

enum
{
	KZ_TILE_SWITCHABLE = 1,
	KZ_TILE_SOLID_STOPPER,
	KZ_TILE_PORTAL_GUN,
	KZ_TILE_PORTAL_ALLOW,
	KZ_TILE_PORTAL_DISALLOW,
	KZ_TILE_PORTAL_RESET,
	KZ_TILE_TURRET,
	KZ_TILE_TURRET_EXPLOSIVE,
	KZ_TILE_DAMAGE_LASER,
	KZ_TILE_SOUND_PLAY,
	KZ_TILE_HEALTH_ZONE,
	KZ_TILE_DAMAGE_ZONE,
	KZ_TILE_MINE,
	KZ_TILE_SOUND_PLAY_LOCAL,
	
	KZ_GAMETILE_NO_DAMAGE = 15,
	KZ_GAMETILE_HITTABLE_SWITCH,

	KZ_FRONTTILE_FORCE_POS = 15,
	KZ_FRONTTILE_KZ_PLAYER_TELEPORT,

	KZ_TILE_SOUND_PLAY_LOCAL_IN_POS,

	KZ_GAMETILE_SPEC_POS = 18,
	KZ_GAMETILE_SWITCHABLE_TEE_ONLY,
	KZ_GAMETILE_SOLID_STOPPER_V2,

	KZ_FRONTTILE_TUNE_SWITCHABLE = 18,
	KZ_FRONTTILE_TUNE_LOCK,
	KZ_FRONTTILE_POS_SHIFTER,
};

enum //KZ Tiles flags
{
	KZ_POS_SWITCHER_FLAG_HOOK = 1,
	KZ_POS_SWITCHER_FLAG_PROJECTILE = 1 << 1,
	KZ_POS_SWITCHER_FLAG_INVERT_VELX = 1 << 2,
	KZ_POS_SWITCHER_FLAG_INVERT_VELY = 1 << 3,

	KZ_HITTABLE_SWITCH_FLAG_NO_HAMMER = 1,
	KZ_HITTABLE_SWITCH_FLAG_GUN = 1 << 1,
	KZ_HITTABLE_SWITCH_FLAG_GRENADE = 1 << 2,
	KZ_HITTABLE_SWITCH_FLAG_SHOTGUN = 1 << 3,
	KZ_HITTABLE_SWITCH_FLAG_LASER = 1 << 4,
	KZ_HITTABLE_SWITCH_FLAG_NINJA = 1 << 5,

};

enum
{
	KZ_CUSTOM_WEAPONS_START = NUM_WEAPONS,
	KZ_CUSTOM_WEAPON_PORTAL_GUN = NUM_WEAPONS,
	KZ_NUM_CUSTOM_WEAPONS,
};

class CKZTile
{
public:
	unsigned char m_Index;
	unsigned char m_Flags;
	unsigned char m_Number;
	int64_t m_Value1;
    int64_t m_Value2;
    int64_t m_Value3;
};

inline int64_t BitWiseAndInt64(int64_t a, int64_t b)
{
	return (a & b);
}

#endif