// Copyright (C) Benjamín Gajardo (also known as +KZ)

#ifndef GAME_VERSION_KZ_H
#define GAME_VERSION_KZ_H

//Kaizo Network

#define KAIZO_NETWORK_VERSION_DDNET // No Custom Messages
#define KAIZO_NETWORK_VERSION_CROWNS 1
#define KAIZO_NETWORK_VERSION_TURRETS 2
#define KAIZO_NETWORK_VERSION_PORTAL_ATTRACTOR 3 // First Released Version
#define KAIZO_NETWORK_VERSION_INSTASHIELD_SHIELD 4
#define KAIZO_NETWORK_VERSION_PLAYER_PING 5

#define KAIZO_NETWORK_VERSION_LATEST KAIZO_NETWORK_VERSION_PLAYER_PING

//Kaizo Client

#define KAIZO_GAME_NAME "Kaizo Client"
#undef GAME_NAME
#define GAME_NAME KAIZO_GAME_NAME

#define KAIZO_CLIENT_VERSION_LATEST 12
#define KAIZO_CLIENT_VERSION_LATEST_STR STRINGIFY(KAIZO_CLIENT_VERSION_LATEST)

#endif